"use client";
import Link from "next/link";
import { useState } from "react";
import { services, slots, staff, tenant } from "@/lib/demo-data";
type Step = "service" | "time" | "customer" | "done";

export function BookingFlow() {
  const [step, setStep] = useState<Step>("service"); const [serviceId, setServiceId] = useState(services[0].id); const [staffId, setStaffId] = useState(staff[0].id); const [slot, setSlot] = useState(slots[0]); const [date, setDate] = useState("2026-09-30"); const [error, setError] = useState(""); const [customer, setCustomer] = useState({ name:"", email:"", phone:"" });
  const service = services.find((item) => item.id === serviceId) ?? services[0]; const professional = staff.find((item) => item.id === staffId) ?? staff[0];
  const updateCustomer = (key: keyof typeof customer, value: string) => setCustomer((current) => ({ ...current, [key]: value }));
  const next = () => { setError(""); if (step === "service") setStep("time"); else if (step === "time") setStep("customer"); };
  async function confirm() { if (!customer.name || !customer.email || !customer.phone) { setError("Preencha nome, e-mail e telefone para continuar."); return; } setError(""); const response = await fetch(`/api/public/${tenant.slug}/appointments`, { method:"POST", headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()}, body:JSON.stringify({ serviceId, staffId, startsAt:`${date}T${slot}:00-03:00`, ...customer }) }); if (!response.ok) { setError("Esse horário acabou de ficar indisponível. Escolha outro para tentar novamente."); return; } setStep("done"); }
  return <div className="booking-wrap"><div className="shell"><header className="booking-header"><Link className="brand" href="/"><span className="brand-mark">M</span>{tenant.name}</Link></header><div className="booking-panel"><div className="stepper" aria-label="Etapas do agendamento"><div className={`step ${step === "service" ? "active" : ""}`}>1. Serviço</div><div className={`step ${step === "time" ? "active" : ""}`}>2. Horário</div><div className={`step ${step === "customer" ? "active" : ""}`}>3. Dados</div><div className={`step ${step === "done" ? "active" : ""}`}>4. Confirmado</div></div>
  {step === "service" && <section className="card"><div className="eyebrow">Primeiro passo</div><h1 style={{fontSize:"clamp(2rem,5vw,3.3rem)"}}>Escolha um serviço.</h1><p className="muted">Selecione uma opção para ver os horários disponíveis.</p><div className="choice-grid">{services.map((item) => <button className={`choice ${item.id === serviceId ? "selected" : ""}`} key={item.id} onClick={() => setServiceId(item.id)}><span><strong>{item.name}</strong><small>{item.description} · {item.durationMinutes} min</small></span><span className="choice-price">R$ {item.price?.toFixed(2)}</span></button>)}</div><div className="actions"><button className="button" onClick={next}>Continuar</button></div></section>}
  {step === "time" && <section className="card"><div className="eyebrow">Segundo passo</div><h1 style={{fontSize:"clamp(2rem,5vw,3.3rem)"}}>Escolha seu horário.</h1><p className="muted">A disponibilidade exibida é revalidada no momento da confirmação.</p><div className="form-grid"><label className="field">Dia<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="field">Profissional<select value={staffId} onChange={(event) => setStaffId(event.target.value)}>{staff.filter((item) => item.serviceIds.includes(serviceId)).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><div className="slot-grid">{slots.map((item) => <button className={`slot ${item === slot ? "selected" : ""}`} key={item} onClick={() => setSlot(item)}>{item}</button>)}</div><div className="actions"><button className="button secondary" onClick={() => setStep("service")}>Voltar</button><button className="button" onClick={next}>Continuar</button></div></section>}
  {step === "customer" && <section className="card"><div className="eyebrow">Terceiro passo</div><h1 style={{fontSize:"clamp(2rem,5vw,3.3rem)"}}>Seus dados.</h1><p className="muted">Usaremos essas informações apenas para confirmar o atendimento.</p><div className="summary"><div className="summary-row"><span>Serviço</span><strong>{service.name}</strong></div><div className="summary-row"><span>Data e hora</span><strong>{date} · {slot}</strong></div><div className="summary-row"><span>Profissional</span><strong>{professional.name}</strong></div></div><div className="form-grid"><label className="field">Nome completo<input value={customer.name} onChange={(event) => updateCustomer("name",event.target.value)} autoComplete="name" /></label><label className="field">E-mail<input type="email" value={customer.email} onChange={(event) => updateCustomer("email",event.target.value)} autoComplete="email" /></label><label className="field">Telefone<input value={customer.phone} onChange={(event) => updateCustomer("phone",event.target.value)} autoComplete="tel" /></label></div>{error && <p className="error" role="alert">{error}</p>}<div className="actions"><button className="button secondary" onClick={() => setStep("time")}>Voltar</button><button className="button" onClick={confirm}>Confirmar horário</button></div></section>}
  {step === "done" && <section className="success"><div className="eyebrow">Tudo certo</div><h1 style={{fontSize:"clamp(2rem,5vw,3.3rem)"}}>Horário reservado.</h1><p>Enviamos o resumo para {customer.email}. A equipe também poderá acompanhar este atendimento no painel.</p><div className="actions"><Link className="button" href="/">Voltar ao início</Link><Link className="button secondary" href="/painel">Abrir painel</Link></div></section>}
  </div></div></div>;
}
